import sys
import os
import shutil
from pathlib import Path
import subprocess

# Add project root to sys.path
sys.path.append(os.getcwd())

from kit import api

def test_plugins_and_safety():
    test_root = Path("test_plugin_root").resolve()
    if test_root.exists():
        shutil.rmtree(test_root)
    test_root.mkdir()
    (test_root / ".git").mkdir()
    
    old_cwd = os.getcwd()
    os.chdir(test_root)
    
    try:
        api.init_kernel()
        brain = api.get_brain()

        # 1. Test Manifest Safety (Markers)
        agents_file = test_root / "AGENTS.md"
        manual_header = "# My Manual Rules\nBe nice to the AI.\n\n"
        with open(agents_file, "w") as f:
            f.write(manual_header)
        
        print("📥 Learning a fact to trigger render...")
        api.learn("arch_fact", "ARCH: Use Rust for performance", importance=1.0)
        
        with open(agents_file, "r") as f:
            content = f.read()
            print("📄 Checking AGENTS.md content...")
            assert manual_header in content, "Manual header was deleted!"
            assert "<!-- GENERATED BY KIT START -->" in content, "Kit markers missing!"
            assert "ARCH: Use Rust" in content, "Architectural fact missing!"
        print("✅ Manifest Safety Verified!")

        # 2. Test Plugin Delegation
        print("\n🛠️ Testing Plugin Delegation...")
        # Create a mock plugin: kit-test.bat (Windows) or kit-test (Unix)
        plugin_name = "kit-test.bat" if os.name == "nt" else "kit-test"
        plugin_path = test_root / plugin_name
        
        if os.name == "nt":
            with open(plugin_path, "w") as f:
                f.write("@echo off\necho PLUGIN_CALLED_SUCCESSFULLY\n")
        else:
            with open(plugin_path, "w") as f:
                f.write("#!/bin/sh\necho PLUGIN_CALLED_SUCCESSFULLY\n")
            plugin_path.chmod(0o755)

        # Add current dir to PATH temporarily
        os.environ["PATH"] = str(test_root) + os.pathsep + os.environ.get("PATH", "")
        print(f"  DEBUG: PATH modified to include {test_root}")
        
        # Call via shell to simulate real CLI use
        kit_script = Path(old_cwd) / "kit.py"
        try:
            result = subprocess.run(
                [sys.executable, str(kit_script), "test"],
                capture_output=True,
                text=True
            )
            print(f"  Plugin Out: {result.stdout.strip()}")
            print(f"  Plugin Err: {result.stderr.strip()}")
            assert "PLUGIN_CALLED_SUCCESSFULLY" in result.stdout, f"Plugin delegation failed! Out: {result.stdout}, Err: {result.stderr}"
            print("✅ Plugin Delegation Verified!")
        except Exception as e:
            print(f"❌ Plugin test error: {e}")
            raise

    finally:
        os.chdir(old_cwd)
        # shutil.rmtree(test_root)

if __name__ == "__main__":
    test_plugins_and_safety()
