import os
import stat
from pathlib import Path


def main():
    git_dir = Path(".git")
    if not git_dir.exists():
        print("Error: .git directory not found. Must run from repository root.")
        return

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)

    pre_commit_path = hooks_dir / "pre-commit"
    
    hook_content = """#!/bin/sh
# Generated by .kit Governance Phase 3

# Capture the commit message logic (for pre-commit, usually it's checking staged changes, but if a message is somehow prepared, we can use it. Otherwise default to a placeholder to satisfy the CLI)
COMMIT_MSG=$(cat .git/COMMIT_EDITMSG 2>/dev/null)
if [ -z "$COMMIT_MSG" ]; then
    COMMIT_MSG="fix: automatic preflight verification"
fi

echo "🛡️ Running Cognitive Gatekeeper..."
# Explicitly use python -m kit.cli.main since kit might not be in PATH
python -m kit.cli.main preflight --strict --message "$COMMIT_MSG"

if [ $? -eq 2 ]; then
  echo ""
  echo "❌ Blocked by Cognitive Gate"
  exit 1
fi
"""
    
    with open(pre_commit_path, "w", encoding="utf-8", newline='\n') as f:
        f.write(hook_content)
        
    # Make executable on Unix
    if os.name == 'posix':
        st = os.stat(pre_commit_path)
        os.chmod(pre_commit_path, st.st_mode | stat.S_IEXEC)
        
    print(f"✅ Successfully installed Git pre-commit hook at {pre_commit_path}")

if __name__ == "__main__":
    main()
